### ISSUE TITLE
Finalizar chamado em aberto

### ISSUE THREAD

**Issue by viniciusdebruin** [AutoAtende/AutoAtende#1]
Mesmo sem ter colocado nenhuma mensagem, ao finalizar alguns chamados do dia passado ele simplesmente jogou de volta alguns dos tickets finalizados na lista de aguardo e disparou a mensagem

Mensagem automática:
Foi transferido para o atendente Vinícius  por Vinícius  em 09/05/2024 11:22:56
Aguarde, já vamos te atender!

Como se eu tivesse aceito o chamado

![Imagem do WhatsApp de 2024-05-09 à(s) 11 23 35_23f58279](https://github.com/AutoAtende/AutoAtende/assets/39091387/fb3639f0-579b-4499-bc7c-701201928979)

![Imagem do WhatsApp de 2024-05-09 à(s) 11 23 50_7118faeb](https://github.com/AutoAtende/AutoAtende/assets/39091387/bf4f6d9c-ee05-4a19-a2ce-5e8310f36c2b)

![image](https://github.com/AutoAtende/AutoAtende/assets/39091387/7ca3d2f3-caa7-4a32-9944-4477cb514a57)

**Comment by LucasSaud** [comment]
Corrigido
