### ISSUE TITLE
Arquivos enviados não abrem

### ISSUE THREAD

**Issue by Marcos-Rodrigo-Cruz** [AutoAtende/AutoAtende#15]
1. Arquivos enviado pelo aparelho celular no WhatsApp oficial ou pela plataforma não abre na plataforma.
2. Todos os formatos de aquivos
3. Adio enviado pelo sistema da erro e não envia.

Segue abaixo exemplo de alguns arquivos

![Audio](https://github.com/AutoAtende/AutoAtende/assets/156728227/f62e961d-4e84-4609-bf2b-9bf5541d2f39)
![Audio2](https://github.com/AutoAtende/AutoAtende/assets/156728227/f08d987b-eee7-4422-b81f-d49114879436)
![Audio3](https://github.com/AutoAtende/AutoAtende/assets/156728227/b108d1f8-e2ee-4f6c-8fc9-30209879936b)

**Comment by LucasSaud** [comment]
Isso já está resolvido.
