### ISSUE TITLE
mensagem saldação e trasfrencia

### ISSUE THREAD

**Issue by Marcao69** [AutoAtende/AutoAtende#19]
nao envia mensagem de saldação e trasferencia, mesmo abilitando nas configuração,

**Comment by viniciusdebruin** [comment]
Eu entendi o que ele quis dizer, eu gravei até um vídeo para o Lucas explicando isso. Vou postar aqui
![image](https://github.com/AutoAtende/AutoAtende/assets/39091387/2500c2dc-0650-431c-8e15-a77621d61276)
Em configurações, independente do que você faça, ele sempre volta para essas opções
![image](https://github.com/AutoAtende/AutoAtende/assets/39091387/0d2332d9-ccdd-4674-90a4-1a6b2b860a89)
Habilitei o Enviar Saudações
![image](https://github.com/AutoAtende/AutoAtende/assets/39091387/a47108b3-30c1-48d9-9541-b3477bbf2303)
Ao atualizar a página, ele volta como estava. Ou seja, ele exibe a mensagem que esta salvando, mas não salva

obs: Não tenho acesso a minha VPS, deixei o controle total com o Lucas

**Comment by LucasSaud** [comment]
Ambos foram corrigidos.
