### ISSUE TITLE
Tarefas não aparecem como deveria em notificação

### ISSUE THREAD

**Issue by Marcos-Rodrigo-Cruz** [AutoAtende/AutoAtende#20]
Ao descrever uma tarefa e salva-la para aparecer como notificação não aparece o que foi escrito.

![tarefa](https://github.com/AutoAtende/AutoAtende/assets/156728227/08f50228-ee0a-4a39-b0d2-04ec5b32c5c4)
![tarefa 02](https://github.com/AutoAtende/AutoAtende/assets/156728227/31d42f3f-3267-4619-9489-4253a46eed9e)

**Comment by LucasSaud** [comment]
Tarefa não gera notificação. Onde o senhor está apontando exibe *INFORMATIVOS*
