### ISSUE TITLE
(Adição) Botão de finalizar chamado sem disparo de mensagem

### ISSUE THREAD

**Issue by gabrielreis02** [AutoAtende/AutoAtende#21]
Em versões anteriores tinha um botão que finalizava o chamado que está em aguardando sem enviar nenhuma mensagem porem nessa nova versão foi adicionado o botão "Recusar Atendimento" porem ele envia uma mensagem de finalização e seria interessante um botão que finalizasse sem enviar nada. O único botão que faz isso nessa versão seria o "Fechar todos" que fecha todos os chamados em aberto porem seria bom poder fechar chamados específicos.

![Captura de tela 2024-05-16 094800](https://github.com/AutoAtende/AutoAtende/assets/95652940/109f9dd7-7c1f-4d88-9e3a-c0629002f88d)

![Captura de tela 2024-05-16 094808](https://github.com/AutoAtende/AutoAtende/assets/95652940/f0508c7a-86e4-4303-99ed-1c42f9d12b75)

**Comment by LucasSaud** [comment]
Só fecha o chamado com mensagem se você definir a mensagem de encerramento

**Comment by gabrielreis02** [comment]
porem tem contatos que tem que aparecer a mensagem de finalização e outros não.

**Comment by viniciusdebruin** [comment]
Desculpa Lucas, mas isso é inviável, uma vez que nós utilizamos uma mensagem padrão para todos os clientes.
Pensa o seguinte, estou conversando com você que tem um typebot implantado e que todo recado pede para digitar 1 ou 2.
Isso para alguns contatos ter a mensagem de finalização é péssimo. Eu mesmo utilizo a mensagem colocando para a pessoa não responder.
Eu e nenhum um cliente vamos remover uma mensagem de encerramento, para encerrar um contato que não queremos que receba o recado e depois voltar e salvar para ter o recado.
Tem clientes que eu não quero que eles saibam que eu fechei o ticket, outros eu preciso que saiba

**Comment by viniciusdebruin** [comment]
olha na pratica o problema

![Captura de tela 2024-05-20 142422](https://github.com/AutoAtende/AutoAtende/assets/39091387/f7cc54f4-e828-4c98-ac08-e74b5a0ace90)


![image](https://github.com/AutoAtende/AutoAtende/assets/39091387/9b9a3409-0be4-4870-acf7-4a22218b7d6c)
