### ISSUE TITLE
Erro na tela de cadastrar fila

### ISSUE THREAD

**Issue by Marcos-Rodrigo-Cruz** [AutoAtende/AutoAtende#23]
Acontece um erro ao cadastrar a fila, quando não é selecionado o tempo e a fila aleatória. O ideal que a mensagem de erro fosse corrigida avisando o que está faltando, ou já ficasse pre-selecionando o tempo com o botão da fila aleatoria desativado, já que o cliente não tem conhecimento do sistema, e tem que ser algo intuitivo. 

![adicionar fila erro](https://github.com/AutoAtende/AutoAtende/assets/156728227/366a11c1-0aec-4c09-8647-36323b1c66a6)

**Comment by LucasSaud** [comment]
Essa função foi removida.
