### ISSUE TITLE
Número Conectado anda não aparece

### ISSUE THREAD

**Issue by quickerboom** [AutoAtende/AutoAtende#3]
o campo esta disponível porém o número conectado ainda não aparece.

![testesdo marcelo1](https://github.com/AutoAtende/AutoAtende/assets/144612429/b094c19a-7049-4bdb-8c57-ebbc7fe82ffa)

e esta dando um erro 

![testesdo marcelo2](https://github.com/AutoAtende/AutoAtende/assets/144612429/6debda4d-0cfe-46b0-b1bb-afbd8e14f030)

**Comment by LucasSaud** [comment]
Corrigido
