### ISSUE TITLE
Fechar todas as conversar no tema Dark

### ISSUE THREAD

**Issue by viniciusdebruin** [AutoAtende/AutoAtende#9]
![image](https://github.com/AutoAtende/AutoAtende/assets/39091387/cd4dcbc7-cf68-4479-9158-a654f784d983)

![image](https://github.com/AutoAtende/AutoAtende/assets/39091387/beab9bb1-e4d1-4ad6-b225-b8215845b6c6)

Agora no tema normal

![image](https://github.com/AutoAtende/AutoAtende/assets/39091387/4efd4bbc-66c8-4f08-82e0-e7078a19c996)

**Comment by LucasSaud** [comment]
corrigido na versao 1.7.5
